name: make twrp

on:
  workflow_dispatch:
    inputs:
      LIBRARY_URL:
        description: 'LIBRARY_URL'
        required: true
        default: 'https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git'
      LIBRARY_BRANCH:
        description: 'LIBRARY_BRANCH'
        required: true
        default: 'twrp-12.1'
      DEVICE_URL:
        description: 'DEVICE_URL'
        required: true
        default: 'https://github.com/zhlhlf/twrp_device_oneplus_lemonades'
      DEVICE_BRANCH:
        description: 'DEVICE_BRANCH'
        required: true
        default: 'oplus-android-13'
      DEVICE_PATH:
        description: 'DEVICE_PATH'
        required: true
        default: 'device/oneplus/lemonades'
      DEVICE_NAME:
        description: 'DEVICE_NAME'
        required: true
        default: 'twrp_lemonades-eng'
        
env:
  ssh: a
  

jobs:
 build:
  runs-on: ubuntu-20.04

  steps:
    - name: Check Out
      uses: actions/checkout@main
      
    - name: 打扫空间
      uses: rokibhasansagar/slimhub_actions@main

    - name: 配置环境
      run: |
        git clone https://github.com/akhilnarang/scripts
        sudo bash scripts/setup/android_build_env.sh
        sudo bash scripts/setup/install_android_sdk.sh || echo 'by zhlhlf'\n
        sudo curl --create-dirs -L -o /usr/local/bin/repo -O -L https://storage.googleapis.com/git-repo-downloads/repo
        sudo chmod a+x /usr/local/bin/repo
              
    - name: 拉取源码
      run: |
        git config --global user.name "zhlhlf"
        git config --global user.email "zhlhlf@gmail.com"
        repo init --depth=1 -u ${{ github.event.inputs.LIBRARY_URL }} -b ${{ github.event.inputs.LIBRARY_BRANCH }}
        repo sync -j$(nproc --all) --force-sync
        rm -r .repo
        ls -a  
    - name: 创建swap内存                
      run: |
         df -h
         export SWAP_FILE=$(swapon --show=NAME | tail -n 1)
         sudo swapoff $SWAP_FILE
         sudo rm $SWAP_FILE
         sudo fallocate -l 12G $SWAP_FILE
         sudo chmod 600 $SWAP_FILE
         sudo mkswap $SWAP_FILE
         sudo swapon $SWAP_FILE
         free -h
          
    - name: 拉取设备树
      run: |
        df -h /
        free -m
        git clone ${{ github.event.inputs.DEVICE_URL }} -b ${{ github.event.inputs.DEVICE_BRANCH }} ${{ github.event.inputs.DEVICE_PATH }}
   
    - name: ssh连接
      if: env.ssh == 'true'                
      run: |
         sudo bash ssh.sh
         
    - name: 构建镜像
      run: |
         source build/envsetup.sh
         export ALLOW_MISSING_DEPENDENCIES=true
         export LC_ALL=C
         lunch ${{ github.event.inputs.DEVICE_NAME }}
         make recoveryimage -j$(nproc --all)

    - name: 上传镜像到我的OneDrive
      run: |
         mkdir 666
         cp -r ./out/target/product/*/recovery.img 666/
         curl -SL https://raw.githubusercontent.com/zhlhlf/text/main/onedrive_mount.sh | sh
           
